org: helloghost0100
app: transcript-gpt
service: transcript-gpt

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-wsgi

custom:
  serverless-offline:
    httpPort: 3003
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
  wsgi:
    app: handler.app

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - venv/**
    - .venv/**

provider:
  name: aws
  runtime: python3.9
  region: "ap-southeast-1"
  ecr:
    images:
      searxng:
        uri: 260805927454.dkr.ecr.ap-southeast-1.amazonaws.com/flexfunc/searxng:latest
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::transcript-gpt-audios/*
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
      Resource: "*"
    - Effect: Allow
      Action:
        - ses:SendRawEmail
        - ses:SendEmail
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: arn:aws:ssm:ap-southeast-1:260805927454:parameter/FlexFuncPrivateKey
    - Effect: Allow
      Action:
        - ecr:BatchGetImage
        - ecr:DeleteRepositoryPolicy
        - ecr:GetDownloadUrlForLayer
        - ecr:GetRepositoryPolicy
        - ecr:SetRepositoryPolicy
      Resource: arn:aws:ecr:ap-southeast-1:260805927454:repository/flexfunc/searxng
    - Effect: Allow
      Action: ecr:DescribeRepositories
      Resource: "*"

functions:
  webSearch:
    runtime: python3.9
    handler: handler.lambda_handler
    events:
      - http:
          method: get
          path: /web-search
          cors: true
